version: "3.7"

services:
  app:
    build: .
    container_name: go-rpi-dashboard
    restart: always
    volumes:
      - ./conf:/conf
      - ./logs:/logs
      - ./templates:/templates
    ports:
      - "9001:9001"